// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateHeroArgs {
    pub name: String,
}

impl From<CreateHeroArgs> for super::Reducer {
    fn from(args: CreateHeroArgs) -> Self {
        Self::CreateHero { name: args.name }
    }
}

impl __sdk::InModule for CreateHeroArgs {
    type Module = super::RemoteModule;
}

pub struct CreateHeroCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_hero`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_hero {
    /// Request that the remote module invoke the reducer `create_hero` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_hero`] callbacks.
    fn create_hero(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_hero`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateHeroCallbackId`] can be passed to [`Self::remove_on_create_hero`]
    /// to cancel the callback.
    fn on_create_hero(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateHeroCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_hero`],
    /// causing it not to run in the future.
    fn remove_on_create_hero(&self, callback: CreateHeroCallbackId);
}

impl create_hero for super::RemoteReducers {
    fn create_hero(&self, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_hero", CreateHeroArgs { name })
    }
    fn on_create_hero(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateHeroCallbackId {
        CreateHeroCallbackId(self.imp.on_reducer(
            "create_hero",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateHero { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_create_hero(&self, callback: CreateHeroCallbackId) {
        self.imp.remove_on_reducer("create_hero", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_hero`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_hero {
    /// Set the call-reducer flags for the reducer `create_hero` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_hero(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_hero for super::SetReducerFlags {
    fn create_hero(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_hero", flags);
    }
}
