// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Hero {
    pub id: u64,
    pub player_identity: __sdk::Identity,
    pub name: String,
    pub x: f32,
    pub y: f32,
    pub health: i32,
    pub max_health: i32,
    pub fame_local: u32,
    pub fame_city: u32,
    pub fame_realm: u32,
    pub fame_godly: u32,
    pub is_alive: bool,
}

impl __sdk::InModule for Hero {
    type Module = super::RemoteModule;
}
