// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::keep_type::Keep;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `keep`.
///
/// Obtain a handle from the [`KeepTableAccess::keep`] method on [`super::RemoteTables`],
/// like `ctx.db.keep()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.keep().on_insert(...)`.
pub struct KeepTableHandle<'ctx> {
    imp: __sdk::TableHandle<Keep>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `keep`.
///
/// Implemented for [`super::RemoteTables`].
pub trait KeepTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`KeepTableHandle`], which mediates access to the table `keep`.
    fn keep(&self) -> KeepTableHandle<'_>;
}

impl KeepTableAccess for super::RemoteTables {
    fn keep(&self) -> KeepTableHandle<'_> {
        KeepTableHandle {
            imp: self.imp.get_table::<Keep>("keep"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct KeepInsertCallbackId(__sdk::CallbackId);
pub struct KeepDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for KeepTableHandle<'ctx> {
    type Row = Keep;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Keep> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = KeepInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KeepInsertCallbackId {
        KeepInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KeepInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = KeepDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KeepDeleteCallbackId {
        KeepDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KeepDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Keep>("keep");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct KeepUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for KeepTableHandle<'ctx> {
    type UpdateCallbackId = KeepUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KeepUpdateCallbackId {
        KeepUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KeepUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Keep>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Keep>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `keep`,
/// which allows point queries on the field of the same name
/// via the [`KeepIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.keep().id().find(...)`.
pub struct KeepIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Keep, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> KeepTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `keep`.
    pub fn id(&self) -> KeepIdUnique<'ctx> {
        KeepIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> KeepIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Keep> {
        self.imp.find(col_val)
    }
}
