// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Keep {
    pub id: u64,
    pub owner_identity: Option<__sdk::Identity>,
    pub name: String,
    pub x: f32,
    pub y: f32,
    pub fortification_level: u32,
    pub resource_bonus: f32,
}

impl __sdk::InModule for Keep {
    type Module = super::RemoteModule;
}
