// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveHeroArgs {
    pub hero_id: u64,
    pub new_x: f32,
    pub new_y: f32,
}

impl From<MoveHeroArgs> for super::Reducer {
    fn from(args: MoveHeroArgs) -> Self {
        Self::MoveHero {
            hero_id: args.hero_id,
            new_x: args.new_x,
            new_y: args.new_y,
        }
    }
}

impl __sdk::InModule for MoveHeroArgs {
    type Module = super::RemoteModule;
}

pub struct MoveHeroCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_hero`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_hero {
    /// Request that the remote module invoke the reducer `move_hero` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_move_hero`] callbacks.
    fn move_hero(&self, hero_id: u64, new_x: f32, new_y: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `move_hero`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MoveHeroCallbackId`] can be passed to [`Self::remove_on_move_hero`]
    /// to cancel the callback.
    fn on_move_hero(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &f32, &f32) + Send + 'static,
    ) -> MoveHeroCallbackId;
    /// Cancel a callback previously registered by [`Self::on_move_hero`],
    /// causing it not to run in the future.
    fn remove_on_move_hero(&self, callback: MoveHeroCallbackId);
}

impl move_hero for super::RemoteReducers {
    fn move_hero(&self, hero_id: u64, new_x: f32, new_y: f32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "move_hero",
            MoveHeroArgs {
                hero_id,
                new_x,
                new_y,
            },
        )
    }
    fn on_move_hero(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &f32, &f32) + Send + 'static,
    ) -> MoveHeroCallbackId {
        MoveHeroCallbackId(self.imp.on_reducer(
            "move_hero",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::MoveHero {
                                    hero_id,
                                    new_x,
                                    new_y,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, hero_id, new_x, new_y)
            }),
        ))
    }
    fn remove_on_move_hero(&self, callback: MoveHeroCallbackId) {
        self.imp.remove_on_reducer("move_hero", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `move_hero`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_move_hero {
    /// Set the call-reducer flags for the reducer `move_hero` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn move_hero(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_move_hero for super::SetReducerFlags {
    fn move_hero(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("move_hero", flags);
    }
}
