// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::town_type::Town;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `town`.
///
/// Obtain a handle from the [`TownTableAccess::town`] method on [`super::RemoteTables`],
/// like `ctx.db.town()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town().on_insert(...)`.
pub struct TownTableHandle<'ctx> {
    imp: __sdk::TableHandle<Town>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `town`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TownTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TownTableHandle`], which mediates access to the table `town`.
    fn town(&self) -> TownTableHandle<'_>;
}

impl TownTableAccess for super::RemoteTables {
    fn town(&self) -> TownTableHandle<'_> {
        TownTableHandle {
            imp: self.imp.get_table::<Town>("town"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TownInsertCallbackId(__sdk::CallbackId);
pub struct TownDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TownTableHandle<'ctx> {
    type Row = Town;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Town> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TownInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownInsertCallbackId {
        TownInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TownInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TownDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownDeleteCallbackId {
        TownDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TownDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Town>("town");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct TownUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TownTableHandle<'ctx> {
    type UpdateCallbackId = TownUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TownUpdateCallbackId {
        TownUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TownUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Town>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Town>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `town`,
/// which allows point queries on the field of the same name
/// via the [`TownIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town().id().find(...)`.
pub struct TownIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Town, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TownTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `town`.
    pub fn id(&self) -> TownIdUnique<'ctx> {
        TownIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TownIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Town> {
        self.imp.find(col_val)
    }
}
